### ISSUE TITLE
Assembler error

### ISSUE THREAD

**Issue by madhavanmalolan** [HikoQiu/JNI_INVOKE_FFMPEG#1]
I am doing an ndk build to get the following error message. 
I have copied the .so files to the libs directory, and placed the files in jni folder to the corresponding jni folder on my app. 

```
/var/folders/2p/0jqlz1c94t537_53qn3h8v9h0000gn/T//ccJtcQLv.s: Assembler messages:
/var/folders/2p/0jqlz1c94t537_53qn3h8v9h0000gn/T//ccJtcQLv.s:4105: Error: bad instruction `cmovg r3,r8'
/var/folders/2p/0jqlz1c94t537_53qn3h8v9h0000gn/T//ccJtcQLv.s:4106: Error: bad instruction `cmovg r2,r3'
/var/folders/2p/0jqlz1c94t537_53qn3h8v9h0000gn/T//ccJtcQLv.s:4108: Error: bad instruction `cmovl r1,r3'
/var/folders/2p/0jqlz1c94t537_53qn3h8v9h0000gn/T//ccJtcQLv.s:4110: Error: bad instruction `cmovg r3,r8'
make: *** [/Users/madhavanmalolan/myapp/app/obj/local/armeabi-v7a/objs/myjnitest/ffmpeg.o] Error 1
```

i am using ndk r12b. Is there something that i may be missing

**Comment by HikoQiu** [comment]
Hi, I've not ever encounter this error. 

Maybe  you should compile *.so step by step to do an ndk build. Here're some materials: 
1. http://ffmpeg-android.blogspot.com/
2. http://enoent.fr/blog/2014/06/20/compile-ffmpeg-for-android/
