### ISSUE TITLE
华为5c手机崩溃

### ISSUE THREAD

**Issue by chlss** [HikoQiu/JNI_INVOKE_FFMPEG#3]
请问你用的什么手机跑的demo

**Comment by HikoQiu** [comment]
使用 Nexus 5

**Comment by chlss** [comment]
argv[0] = "ffmpeg";
        argv[1] = "-y";
        argv[2] = "-i";
        argv[3] = "/storage/emulated/0/appwonderroot/v/raw/vedio-1586478489.mp4";
        argv[4] = "-strict";
        argv[5] = "experimental";
        argv[6] = "-b";
        argv[7] = "500";
        argv[8] = "/storage/emulated/0/appwonderroot/v/cps/c-vedio-1586478489-c.mp4";


argv[3]和argv[8]要替换吧？

**Comment by HikoQiu** [comment]
嗯，[3] 是源视频路径， [8]是转码后的视频路径。

**Comment by chlss** [comment]
一直跑不了，请问视频压缩率有多少
